[test]
mailgun_api_key = "QG44oaKk3wuKItRRMVlh6CwNLH5wD7l+5FgWrb00slSkZFk="
foghorn_key = "vScJQ+x33D53JGCgXQmpkCIxOajn7Hs+r+sRMxQWDKmx"
foo_bar = "xRCvh7BKhUdUqWaWrGvq6yszmfgU+FUnkgO65f2SnC010TXF+UA="
key_fun = "IkQOOEbx+l+vYgVIdU+1H4NtkGMkP8Gxm65khGJbjAuuLTsqmw=="
more = "oum0qkWb1vHZk1v1CWUk51BR+ySllOZ7SMluKEgTBUqZDHC9"
teddy = "ShL71v48t3nunR/nAwOJ7JR6+jYIVyHjB8+EFVzkusX9SIdzUHc="
