[test]
mailgun_api_key = "HwrUXiSw3NdYrmeqp2HuUxxqITdYBKUABC/AeAJH5Gr+G6c="
foghorn_key = "Nsv8kwK2sCztxefU6o3YuwTizFTptyhCT7D1Vaq4EpKi"
foo_bar = "HliI0Ta7HYilbf85ztaYIKY5URwJk8eV/pTyJzB/ydVJzD4WF28="
key_fun = "Plg6WuHbI87tU+jWzt22OGh2wcJR/kLvvV7uht12W+shPgiERw=="
more = "tJ/Enrs7FX6MYoN0tQ+ogc5nla+sYqNTfUe/PGqaJkfnWlzt"

