[test]
mailgun_api_key = "8bx4YWF9/H2geVNAV9IY28Jdki2FAMpTaoIEYFlgielag7k="
foghorn_key = "hUHLQfDUwX/XnrRVTUDsUi2nSVtCvjwI2QUri7rBA6Jp"
foo_bar = "bWSsq6y9o4Pm7SmKkKn3G3H+gyy8KjYIQ186z86UeTjpz+xVzPo="
key_fun = "o8tYb4sxGj+Qs6nFKeKdI9GsBVEbh36snuNA+OM2zXvrCmFb8Q=="
more = "cSqe9OMGgXulhK6hiwKkU7jLiHos3ykwOseaGarwhW+aJtB7"
teddy = "ZVgRSerk/ImIxvlX15dehJy0vclcu35/xxZI9aLsJa+lBlmWog=="
